### ISSUE TITLE
Implement device_state_attributes

### ISSUE THREAD

**Issue by RaulVKoNe** [claytonjn/hass-circadian_lighting#179]
After upgrading to Home Assistant 2021.12.0:

Entity switch.circadian_lighting_circadian_lighting (<class 'custom_components.circadian_lighting.switch.CircadianSwitch'>) implements device_state_attributes. Please report it to the custom component author.

Entity sensor.circadian_values (<class 'custom_components.circadian_lighting.sensor.CircadianSensor'>) implements device_state_attributes. Please report it to the custom component author.

**Comment by claytonjn** [comment]
Thanks, I'm a bit behind on updates. I'll try to take care of it as soon as possible so that it doesn't break in future releases, but recently my laptop's touchpad stopped working and my desktop is 8-years-old and has been having OS level issues and won't take updates - if anyone is able to submit a PR that would be much appreciated!

**Comment by claytonjn** [comment]
Released [2.0.6](https://github.com/claytonjn/hass-circadian_lighting/releases/tag/2.0.6) which includes this fix.
