### ISSUE TITLE
Don't automatically prefix entity name with `circadian_lighting_`

### ISSUE THREAD

**Issue by frenck** [claytonjn/hass-circadian_lighting#18]
Please don't prefix generated entity_id's with `circadian_lighting_`, this is not how Home Assistant does this in general.

In my case, it screws with my naming schemes. e.g., I use a naming schema `<domain>.<area>_<name>`

When adhering to my scheme, the switch for my hall would end up being:

`switch.circadian_lighting_hall_circadian_lighting` 😔

**Comment by claytonjn** [comment]
Yes, I plan on making this change. My entities are all the same, with `circadian_lighting` at the beginning and end. I've only held out because I made the poor choice at the beginning and it would be a breaking change. 

If I have enough time to make change https://github.com/claytonjn/hass-circadian_lighting/issues/4 then I will definitely make the change then, as that would be equally breaking.

**Comment by pacobyte** [comment]
Have you had time to begin working on this change? I just installed Circadian Lighting today and was disappointed that the configuration's `name:` property worked differently than the rest of Home Assistant's integrations.

**Comment by claytonjn** [comment]
Unfortunately not, along with this change I also need to update the integration to add everything to the entity registry to allow for changing the entity_id. Really, though, I want to implement this breaking change along with #4 as that would also greatly enhance functionality, but that's a significant amount of work that I unfortunately don't have time for currently.

**Comment by ceesvanegmond** [comment]
@frenck 👍 +1
