### ISSUE TITLE
Support for treaating as one light, from 2 separate channels (cold and warm)

### ISSUE THREAD

**Issue by fusionstream** [claytonjn/hass-circadian_lighting#246]
As above.

Am running esphome with separate light entities for cold channel and warm channel

**Comment by lachmanfrantisek** [comment]
Hi @fusionstream,
If it still helps, I share my experience with these lights since I have double-white lights in my setup as well.

I used [this integration](https://github.com/mion00/color-temperature-light-mixer/) for a while with shelly RGBW2 to provide one light from two entities (shelly supports either RGBW or 4*single channel). Sadly, this does not use the merging mode I like (preserving brightness when changing colour with the downside of reducing max brightness).

Nowadays, I am doing this on esphome level.

**Comment by fusionstream** [comment]
I too have done this actually, using ESPHome to treat 2 channels as a color temperature adjustable single light. Thanks for the message!
