### ISSUE TITLE
not compatible with light.toggle automations

### ISSUE THREAD

**Issue by Viktor45** [claytonjn/hass-circadian_lighting#64]
Hi! 

I found non compatible issues with hass-circadian_lighting and hass switch light.toggle automations.
the issues this caused: light doesnt on/off correctly first time randomly due to on then off during circadian calibrations with brightness/colortemp  (eg im off light with switch with light.toggle, but it doesnt off, it will on again, i need to repeat off procedure). I need to use switches again second or third times to make it works as intended. After disable hass-circadian_lighting any issues are completely gone.

please add something to code to ignore light.toggle with circadian manipulations or investigate this issue more cleanly.

**Comment by claytonjn** [comment]
There is nothing I can do from this from the CL side. The issue is that with some light integrations when you send an off command the light entity turns back on very briefly before this the status is confirmed as off. This happens independently of CL. With CL enabled, it detects the brief on status and tries to adjust the lights which keeps them on. 

I can't ignore light.toggle because then when someone turns on a light and wants it to be adjusted by CL it wouldn't be. The only solution is for your automations to toggle off the CL switch before sending the light.toggle command.

**Comment by Viktor45** [comment]
thank you
